#pragma once

#include <libserialport.h>
#include <stdint.h>

#include <functional>
#include <memory>
#include <stdexcept>
#include <string>

namespace ZanaBlocks::EspTools {
/**
 * @brief Result of a probe() call.
 */
struct ProbeResult {
  bool isMicroPython = false;
  std::string firmwareVersion;  ///< e.g. "1.23.0"
  std::string hardwareModel;    ///< e.g. "ESP32 module with ESP32"
};

/**
 * @brief The state of a command execution.
 */
enum class RUN_STATE : uint8_t {
  ERROR = 0,    ///< Indicates an error occurred during command execution. The
                ///< output string will contain the error message.
  SUCCESS = 1,  ///< Indicates the command executed successfully. The output
                ///< string will contain any output generated by the command.
  TIME_OUT = 2  ///< Indicates that the command execution timed out. The output
                ///< string will contain a timeout message.
};

class ReplClient {
 public:
  /**
   * Progress callback type: receives a message string to display in the UI.
   * You can use it to show progress during file transfers, e.g. "Sent 128/1024
   * bytes". The callback is optional; if not provided, no progress updates will
   * be made.
   */
  using ProgressCallback = std::function<void(const std::string& message)>;

  explicit ReplClient(const std::shared_ptr<sp_port>& connection);

  ~ReplClient();

  // Make immovable and non-copyable
  ReplClient(const ReplClient&) = delete;
  ReplClient& operator=(const ReplClient&) = delete;
  ReplClient(ReplClient&&) = delete;
  ReplClient& operator=(ReplClient&&) = delete;

  /**
   * @brief Run a Python command in the raw REPL and return the output. The
   * command should be a single line of code. The output is captured until the
   * raw REPL prompt (">") is seen, or until a timeout occurs. If the command
   * causes an error on the device, the error message will be included in the
   * output string. Note: the command is sent as-is, so if you want to run
   * multiple lines of code, you should format them with newline characters
   * ("\n") and ensure they are properly indented for Python. The raw REPL will
   * execute the code and return any output or errors generated by it.
   *
   * @param code The Python code to execute on the device. Can be multiple lines
   * if formatted with "\n".
   * @return A pair containing the run state (SUCCESS, ERROR, or TIME_OUT) and
   * the output string from the device.
   */
  std::pair<RUN_STATE, std::string> runPythonCmd(const std::string& code);

  /**
   * @brief Upload a local file to the device's filesystem. The file is read in
   * chunks and sent to the device using the raw REPL. The method handles
   * opening the remote file, writing data in chunks, and closing the file when
   * done. The progress callback is invoked with messages indicating how many
   * bytes have been sent.
   * @param localPath The path to the local file on the host machine.
   * @param remotePath The path where the file should be saved on the device.
   * @param callback An optional callback function that receives progress
   * messages.
   * @return True if the file was successfully uploaded, false otherwise.
   */
  bool putFile(const std::string& localPath, const std::string& remotePath,
               ProgressCallback callback = nullptr);

  /**
   * @brief Reset the device by sending a machine.reset() command. This will
   * cause the device to reboot.
   */
  void reset();  // machine.reset() — full reboot

  /**
   * @brief Probe the device to check if MicroPython is running and retrieve
   * firmware/hardware info.
   *
   * Sends a minimal Python command using sys and os.uname(). Returns a
   * ProbeResult with isMicroPython=false if the device is unresponsive, timed
   * out, or running something else. On success, firmwareVersion and
   * hardwareModel are populated from os.uname().
   */
  ProbeResult probe();

 private:
  void writeAll(const std::string& data);
  std::pair<RUN_STATE, std::string> readUntil(const std::string& marker,
                                              unsigned timeoutMs);
  void enterRawRepl();
  void exitRawRepl() { writeAll("\x02"); }

  /**
   * Note: sp_port is an opaque struct defined in libserialport.h, representing
   a serial port. We store a pointer to it here for managing the connection.
   * The actual file descriptor (m_fd) is obtained from the sp_port and used for
   low-level read/write operations. We keep both for convenience, but we
   primarily use the sp_port API for communication.
   */
  std::shared_ptr<sp_port> mSerialConnection;

  /**
   * The size of each chunk to read/write from the serial port.
   */
  static constexpr std::size_t CHUNK_SIZE = 256;  // bytes per write call
};

}  // namespace ZanaBlocks::EspTools